### PR TITLE
Add S6 service type (longrun)  for PHP and Nginx

### PR DESCRIPTION
**Pull request by thePanz**
This is a first step into moving to the new S6 v3 definitions

### CODE REVIEW

**Comment by eXistenZNL** [comment]
Ah super cool, I am reading up on v3 but don't have a lot of experience with it yet.

Only the PHP 8.3 container is running S6 Overlay V3, the older PHP versions are running V1. Can you remove the files for those versions please?

**Comment by thePanz** [comment]
sure, I can have a look.
Anyway: the "longrun" is the default for S6v1, thus adding them is just for clarity and being explicit about their type

**Comment by thePanz** [comment]
@eXistenZNL changes applied :heavy_check_mark:

**Comment by eXistenZNL** [comment]
Cool! Thx!

**Pull request merged**
